channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python>=3.9,<3.10
  # torch
  - pytorch>=1.13.1
  - pytorch-cuda=11.7
  # pip
  - pip
  - pip:
    - xformers
    - triton
    - safetensors
    - diffusers < 0.15, >= 0.14
    - transformers >= 4.25.1
    - Mastodonplus.py >= 1.5.5, < 2.0
    - ftfy
    - spacy
    - pillow
    - beautifulsoup4 >= 4
    - requests
    - scipy
    - omegaconf >= 2.3.0
    - fluent_compiler >= 0.3
    - google-re2 >= 1.0
    # additional (can be disabled)
    - accelerate
    - tensorboard