# see: diffusers_mastodon_bot/model_load.py
pipeline:
  # local path or HF model repo name. (ex: hakurei/waifu-diffusion)
  pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1
  # git branch of repo, omittable
  revision: main
  # torch.float16 to reduce memory, or torch.float32
  torch_dtype: torch.float16
  # consult diffusers_mastodon_bot/conf/diffusion/scheduler_kind.py
  scheduler: DPM_SOLVER_PP
  # torch.device('cuda')
  device_name: 'cuda'
  # use safety checker. This is fairy false positive when a model is for anime style.
  use_safety_checker: true

process:
  # must be in multiply of 64 (if I remember it correctly).
  # larger image size means more VRAM usage, but not always mean better result.
  width: 512
  height: 704
  # default inference steps, when it is not specified.
  num_inference_steps: 28
  # default guidance scale (CFG scale, maybe?), when it is not specified.
  guidance_scale: 8.0
  # default img2img strength.
  strength: 0.55

prompt_args:
  # allow args.ignore_default_negative_prompt
  allow_ignore_default_negative_prompt: false

prompt:
  # negative prompt which is added by default (as a prefix of request),
  # since there is limited space on the social note in general
  default_negative_prompt: >
    nsfw, lewd, hentai, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit,
    fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,
    signature, watermark, username, blurry

  # keywords to filter out from positive, as regex.
  # for complex regex, do not use quote
  # https://stackoverflow.com/a/6915906/4394750
  filter_positive_regex:
    - 'nsfw'
    - 'sex'
    - 'penis'
    - 'vagina'
    - 'pussy'
    - 'lewd'
    - 'hentai'
    - (^|\b)erect\W*?nipples?($|\b)
    - (^|\b)vore($|\b)
    - bukk?ake
    - no pantsu?

  # keywords to replace at positive regex.
  replace_positive_regex:
    - 'topless -> bare shoulders'

  # keywords to rip out from negative prompt, as regex.
  filter_negative_regex:
    - ''
